### ISSUE TITLE
Incorrect localization for zombie Arlene in Localization.txt. 

### ISSUE THREAD

**Issue by flatlanderone** [arramus/V1.0-Preppocalypse#1]
The localization for zombie Arlene in Localisation.txt seems inconsistent with the other vanilla zombies. 

zombieArlene,entityclasses,Entity,,,Zombies,,,,,,,,,,,,,

**Comment by arramus** [comment]
For players that use Health Bar and can see the name, it will look incorrect.
For players that do not use Health Bar and cannot see the name as intended, it will make no difference.

zombieArlene,entityclasses,Entity,,,Zombies,,,,,,,,,,,,, is currently a place marker.
It is a necessary localization for the Zombie Elimination Quest. The first zombie in the list is shown in the top right area.
Arlene is the first zombie in the list and will show as Zombies.

I will add a fake entity here that cannot spawn but can take the name of Zombies in a future update.
It will be called zombieZombies,entityclasses,Entity,,,Zombies,,,,,,,,,,,,,
I was waiting for TFP to complete zombie additions and updates as announced.
In V1 we have received Bowler and Inmate so far.

**Comment by flatlanderone** [comment]
That clears things up. I play with an HP bar mod and it would come up regularly.

**Comment by arramus** [comment]
The fake entity has been added and Arlene will be second in the list and keep her name.

**Comment by flatlanderone** [comment]
Good stuff.
